FROM python:3.13-alpine AS builder

ARG FOLDER=/app

WORKDIR ${FOLDER}

COPY . /app

RUN <<EOF
python3 -m venv venv
source venv/bin/activate
pip3 install -r requirements.txt --no-cache-dir
EOF

ENV ENV=development

USER 1000:1000

EXPOSE 8000

ENTRYPOINT [ "python3" ]

CMD [ "manage.py", "runserver", "0.0.0.0:8000" ]
