FROM python:3.13-alpine AS builder

ARG FOLDER=/app

WORKDIR ${FOLDER}

COPY --chown=1000:1000 . /app

USER 1000:1000

RUN pip3 install -r requirements.txt --no-cache-dir

ENV ENV=development

EXPOSE 8000

ENTRYPOINT [ "python3" ]

CMD [ "manage.py", "runserver", "0.0.0.0:8000" ]
